name: Pull Requests

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
      - "releases/v*"
  pull_request:
    branches:
      - "releases/v*"
      - development

# Cancel running builds if another push to the PR/branch is made while this build is running
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  # Format PR
  format_check:
    name: Checks Source Code Formatting
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: "temurin"
          java-version: 21

      - uses: Ortus-Solutions/commandbox-action@v1.0.3
        with:
          cmd: run-script format:check

      - name: Verify Code Formatting
        run: ./gradlew spotlessCheck
